### ISSUE TITLE
[Qt 6] Library name

### ISSUE THREAD

**Issue by begin-theadventure** [kuba160/ddb_gui_qt5#5] opened 2024-06-11 19:48 UTC
The `.so` file must be installed as `ddb_gui_qt5.so` instead of `ddb_gui_qt6.so`; otherwise, it doesn't work.
Because of that, the 'GUI Plugin' version appears as `qt5` rather than `qt6` and conflicts with the Qt 5 version.

**Comment by kuba160** [comment] 2024-06-15 14:06
Kind of duplicate of #4

**Closed as completed by kuba160** 2024-06-15 14:06 UTC
